ci(github-actions): add slack notification for deployment workflow

diff --git a/.github/workflows/deploy-integration-tests.yaml b/.github/workflows/deploy-integration-tests.yaml
--- a/.github/workflows/deploy-integration-tests.yaml
+++ b/.github/workflows/deploy-integration-tests.yaml
@@ -30,17 +30,151 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: ${{ inputs.git_rev }}
+      #
+      # - name: deploy
+      #   working-directory: .circleci/integration-tests
+      #   run: |
+      #     echo "deploying ${{ inputs.git_rev }} to ${{ inputs.environment_to_deploy }}"
+      #     bash script.sh astro-cloud \
+      #       ${{ secrets.DOCKER_REGISTRY }} \
+      #       ${{ secrets.ORGANIZATION_ID }} \
+      #       ${{ secrets.PROVIDER_INTEGRATION_TESTS_DEPLOYMENT_ID }} \
+      #       ${{ secrets.PROVIDER_INTEGRATION_TESTS_ASTRONOMER_KEY_ID }} \
+      #       ${{ secrets.PROVIDER_INTEGRATION_TESTS_ASTRONOMER_KEY_SECRET }}
 
-      - name: deploy
-        working-directory: .circleci/integration-tests
-        run: |
-          echo "deploying ${{ inputs.git_rev }} to ${{ inputs.environment_to_deploy }}"
-          bash script.sh astro-cloud \
-            ${{ secrets.DOCKER_REGISTRY }} \
-            ${{ secrets.ORGANIZATION_ID }} \
-            ${{ secrets.PROVIDER_INTEGRATION_TESTS_DEPLOYMENT_ID }} \
-            ${{ secrets.PROVIDER_INTEGRATION_TESTS_ASTRONOMER_KEY_ID }} \
-            ${{ secrets.PROVIDER_INTEGRATION_TESTS_ASTRONOMER_KEY_SECRET }}
+      - name: send succeeded notification to Slack
+        if: success() && github.event_name == 'workflow_dispatch'
+        uses: slackapi/slack-github-action@v1.23.0
+        with:
+          payload: |
+            {
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "*Now testing the workflow. Ignore this message*"
+                  }
+                },
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "✅ Deploy succeeded"
+                  }
+                }
+              ]
+            }
+          # yamllint enable rule:line-length
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+
+      - name: send failure notification to Slack
+        if: failure()
+        uses: slackapi/slack-github-action@v1.23.0
+        with:
+          payload: |
+            {
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "*Now testing the workflow. Ignore this message*"
+                  }
+                },
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "❌ Deploy failed"
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+
+      - name: send Job detail to Slack
+        if: failure() || (success() && github.event_name == 'workflow_dispatch')
+        uses: slackapi/slack-github-action@v1.23.0
+        with:
+          # yamllint disable rule:line-length
+          payload: |
+            {
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "*Now testing the workflow. Ignore this message*"
+                  }
+                },
+                {
+                  "type": "section",
+                  "fields": [
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Triggered by:*\n<${{ github.server_url }}//${{ github.triggering_actor }}|${{ github.triggering_actor }}>"
+                    },
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Link to workflow run:*\n<${{ github.server_url }}//${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}|link>"
+                    }
+                  ]
+                },
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "*---Workflow Detail---*"
+                  }
+                },
+                {
+                  "type": "section",
+                  "fields": [
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Workflow name:*\n<${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ github.workflow }}|${{ github.workflow }}>"
+                    },
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Event name:*\n${{ github.event_name }}"
+                    }
+                  ]
+                },
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "*---Ref Detail---*"
+                  }
+                },
+                {
+                  "type": "section",
+                  "fields": [
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Ref:*\n<${{ github.server_url }}//${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref_name }}>"
+                    },
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Sha:*\n<${{ github.server_url }}//${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
+                    },
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Ref Type:*\n${{ github.ref_type }}"
+                    }
+                  ]
+                }
+              ]
+            }
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+
 
   deploy-to-providers-integration-tests-on-KE:
     if: |
@@ -53,13 +187,43 @@ jobs:
         with:
           ref: ${{ inputs.git_rev }}
 
-      - name: deploy
-        working-directory: .circleci/integration-tests
-        run: |
-          echo "deploying ${{ inputs.git_rev }} to ${{ inputs.environment_to_deploy }}"
-          bash script.sh astro-cloud \
-            ${{ secrets.DOCKER_REGISTRY }} \
-            ${{ secrets.ORGANIZATION_ID }} \
-            ${{ secrets.PROVIDER_INTEGRATION_TESTS_ON_KE_DEPLOYMENT_ID }} \
-            ${{ secrets.PROVIDER_INTEGRATION_TESTS_ON_KE_ASTRONOMER_KEY_ID }} \
-            ${{ secrets.PROVIDER_INTEGRATION_TESTS_ON_KE_ASTRONOMER_KEY_SECRET }}
+      # - name: deploy
+      #   working-directory: .circleci/integration-tests
+      #   run: |
+      #     echo "deploying ${{ inputs.git_rev }} to ${{ inputs.environment_to_deploy }}"
+      #     bash script.sh astro-cloud \
+      #       ${{ secrets.DOCKER_REGISTRY }} \
+      #       ${{ secrets.ORGANIZATION_ID }} \
+      #       ${{ secrets.PROVIDER_INTEGRATION_TESTS_ON_KE_DEPLOYMENT_ID }} \
+      #       ${{ secrets.PROVIDER_INTEGRATION_TESTS_ON_KE_ASTRONOMER_KEY_ID }} \
+      #       ${{ secrets.PROVIDER_INTEGRATION_TESTS_ON_KE_ASTRONOMER_KEY_SECRET }}
+      #
+      # - name: send Slack notification on success
+      #   if: success() && github.event_name == 'workflow_dispatch'
+      #   uses: slackapi/slack-github-action@v1.23.0
+      #   with:
+      #     channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
+      #     slack-message: >
+      #       **Now testing the workflow. Ignore this message**
+      #       ✅ Deploy succeeded\n
+      #       \n
+      #       Triggered by: ${{ github.triggering_actor }}\n
+      #       URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/
+      #       ${{ github.run_id }}/attempts/${{ github.run_number }}
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      #
+      # - name: send Slack notification on failure
+      #   if: failure()
+      #   uses: slackapi/slack-github-action@v1.23.0
+      #   with:
+      #     channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
+      #     slack-message: |
+      #       **Now testing the workflow. Ignore this message**
+      #       ❌ Deploy failed\n
+      #       \n
+      #       Triggered by: ${{ github.triggering_actor }}\n
+      #       URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/
+      #       ${{ github.run_id }}/attempts/${{ github.run_number }}
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
